<?php

namespace App\Repositories;

use App\Http\Resources\MembreResource;
use App\IRepositories\IMembreRepository;
use App\Models\Membre;
use Carbon\Carbon;
use Illuminate\Support\Str;

class MembreRepository extends Repository implements IMembreRepository
{

    public function __construct(Membre $membre)
    {
        parent::__construct($membre);
    }

    function create(array $input)
    {
        $input['nom']=Str::upper($input['nom']);
        $input['prenom']=Str::title($input['prenom']);
        $input['civilite']=Str::ucfirst($input['civilite']);
        $input['dateinscription']=Carbon::parse($input['dateinscription'])->format('Y-m-d');
        return parent::create($input);
    }

    function delete($id)
    {
        return parent::delete($id);
    }

    function findById($id)
    {
        return parent::findById($id);
    }

    function update(array $input, $id)
    {
        $current=$this->findById($id);
        $input['nom']=isset($input['nom'])? Str::upper($input['nom']):$current->nom;
        $input['prenom']=isset($input['prenom'])? Str::title($input['prenom']):$current->prenom;
        $input['civilite']=isset($input['civilite'])? Str::ucfirst($input['civilite']):$current->civilite;
        $input['fkrole']= $input['fkrole'] ?? $current->fkrole;
        $input['dateinscription']=isset($input['dateinscription'])? Carbon::parse($input['dateinscription'])->format('Y-m-d')
            :$current->dateinscription;
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    function index()
    {
        return MembreResource::collection(parent::index());
    }


    function getActiveMember()
    {
        $membres=Membre::ActiveMember()
                ->orderBy('nom','asc')
                ->orderBy('prenom','asc')
                ->get();
        return MembreResource::collection($membres);
    }
}
