<?php

namespace App\Repositories;

use App\Http\Resources\TypeArticleResource;
use App\Models\Typearticle;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class TypeArticleRepository extends Repository
{
    public function __construct(Typearticle $typearticle)
    {
        parent::__construct($typearticle);
    }

    function create(array $input)
    {
        $input['typearticle']=Str::upper($input['typearticle']);
        return parent::create($input);
    }

    function delete($id)
    {
        return parent::delete($id);
    }

    function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    function update(array $input, $id)
    {
        $current=$this->findById($id);
        $input['typearticle']=isset($input['typearticle'])? Str::upper($input['typearticle']):
            $current->typearticle;
        return parent::update($input, $id);
    }

    function index()
    {
        $cacheKey = 'typearticles';
        $typearticles=Cache::remember($cacheKey,now()->addDay(),function(){
            return TypeArticleResource::collection(parent::index()->sortBy('typearticle')->values())->resolve() ;
        });
        return $typearticles;

    }

}
