<?php

namespace App\Repositories;

use App\Http\Resources\TypeMessageResource;
use App\Models\Typemessage;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class TypeMessageRepository extends Repository
{
    public function __construct(Typemessage $typeMessage)
    {
        parent::__construct($typeMessage);
    }

    function create(array $input)
    {
        $input['typemessage']=Str::title($input['typemessage']);
        $input['slug']=Str::slug($input['typemessage']);
        return parent::create($input);
    }

    function delete($id)
    {
        return parent::delete($id);
    }

    function findById($id)
    {

        return new TypeMessageResource(parent::findById($id)) ; // TODO: Change the autogenerated stub
    }

    function update(array $input, $id)
    {
        $current=$this->findById($id);
        $input['typemessage']=isset($input['typemessage'])? Str::title($input['typemessage']):
            $current->typemessage;
        if(isset($input['typemessage'])){
            $input['slug']=Str::slug($input['typemessage']);
        }
        return parent::update($input, $id); //
    }

    function index()
    {
        $cacheKey = 'typemessages';
        //Cache::forget($cacheKey);
        //dd(parent::index());
        $typemessages=Cache::remember($cacheKey,now()->addDay(),function(){
            return TypeMessageResource::collection(parent::index()->sortBy('typemessage')->values())->resolve() ;
        });
        return $typemessages;
    }

}
