<?php

namespace App\Repositories;

use App\Helpers\Helper;
use App\Http\Resources\VideoResource;
use App\Models\Video;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class VideoRepository extends Repository
{
    public function __construct(Video $video)
    {
        parent::__construct($video);
    }

    function create(array $input)
    {
        $input['titre']=Str::ucfirst($input['titre']);
        $input['video']=Helper::getYoutubeKey($input['video']);
        return parent::create($input);
    }

    function delete($id)
    {
        return parent::delete($id);
    }

    function findById($id)
    {
        return new VideoResource(parent::findById($id))  ;
    }

    function update(array $input, $id)
    {
        $current=$this->findById($id);
        $input['titre']=isset($input['titre'])? Str::ucfirst($input['titre']):$current->titre;
        $input['video']= Helper::getYoutubeKey($input['video']) ?? $current->video;
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }
    private function videoList(){
         return  Video::VideoList()->limit(30)->get();
    }
    function index()
    {
        return  VideoResource::collection(
            $this->videoList()
                //->orderByDesc('created_at')
                //->get()
        ) ;
    }
    function getVideoList(){
        //Cache::forget('random_videos_pool');
        $cacheKey="random_videos_pool";
        $cacheExpiry=now()->addMinutes(30);
        //Cache::forget($cacheKey);
        return Cache::remember($cacheKey , $cacheExpiry, function () {
            return VideoResource::collection($this->videoList())->resolve();
        });

    }
    function getRandomVideo(){
        Cache::forget('random_videos_pool');
        $video = $this->videoList()
            ->shuffle()
            ->take(1);
        return  VideoResource::collection($video);
    }
}
