<?php

namespace App\Repositories;

use App\Http\Resources\VideoResource;
use App\Models\Video;
use Illuminate\Support\Str;

class VideoRepository extends Repository
{
    public function __construct(Video $video)
    {
        parent::__construct($video);
    }

    function create(array $input)
    {
        $input['titre']=Str::ucfirst($input['titre']);
        return parent::create($input);
    }

    function delete($id)
    {
        return parent::delete($id);
    }

    function findById($id)
    {
        return new VideoResource(parent::findById($id))  ;
    }

    function update(array $input, $id)
    {
        $current=$this->findById($id);
        $input['titre']=isset($input['titre'])? Str::ucfirst($input['titre']):$current->titre;
        $input['video']= $input['video'] ?? $current->video;
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }
    private function videoList(){
         $videos=Video::orderByDesc('created_at')->limit(50)->get();
         return  VideoResource::collection($videos) ;
    }
    function index()
    {
        return  VideoResource::collection(parent::index()->sortByDesc('created_at')) ;
    }
    function getVideoList(){
        return  $this->videoList() ;
    }
}
